# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#addons

#------------------Navigation 1-----------------------------------

cartographer = Addon.create(name: "Cartographer", description: "Cartographer is a modular, lightweight, and efficient framework for manipulation of the world map.", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://screenshots.en.sftcdn.net/en/scrn/61000/61072/world-of-warcraft-cartographer-add-on-9.jpg", dtime: 20, downloadlink: "/addons/maps/Cartographer.zip")
alphamap = Addon.create(name: "AlphaMap", description: "AlphaMap is a scalable, moveable, transparent WorldMap that the user can have on screen while they continue to play and interact with the world. ", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://legacy.curseforge.com/media/images/0/92/alphamap-alpha-map.jpg", dtime: 20, downloadlink: "/addons/maps/AlphaMap.zip")
zonelevel = Addon.create(name: "ZoneLevel", description: "ZoneLevel will display your zone and level on the world map, and display the level of the zone you are currently viewing. We are working on a way for you to shut this off if you like. Also ZoneLevel will do a bunch of other small things, such as show fps, honor, your current level, todays honor/kills, and display cords.", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://legacy.curseforge.com/media/images/46/458/WoWScrnShot_093012_005840.jpg", dtime: 20, downloadlink: "/addons/maps/ZoneLevel.zip")
cleanmini = Addon.create(name: "CleanMiniMap", description: "A clean square or round minimap that replaces the default minimap. Cleans up default buttons and rearranges them. The minimap and buttons can be individually scaled and various portions of the map can be hidden. ", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://media-curse.cursecdn.com/attachments/13/159/44de33041b2614cd4d4cecb1ea36b7f3.jpg", dtime: 20, downloadlink: "/addons/maps/CleanMinimap")
questlevel = Addon.create(name: "QuestLevels", description: "This addon simply adds the otherwise-hidden level as a prefix before each quest's entry in the quest log or the watched quest list. ", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://media-curse.cursecdn.com/attachments/12/249/7d0b1d494489ca2a987968ecbd9e64c9.jpg", dtime: 20, downloadlink: "/addons/maps/QuestLevels.zip")
corner = Addon.create(name: "CornerMiniMap", description: "This addon will give a better shape to your minimap.", category: "Maps/Navigation", support: "Version 1.12.1", category_id: 1, image: "http://legacy.curseforge.com/thumbman/images/3/767/195x200/cornerminimap-version-b.jpg.-m1.png", dtime: 20, downloadlink: "/addons/maps/CornerMinimap.zip")


#------------------ UI 2-------------------------------------------

xperl = Addon.create(name: "X-perl", description: "A complete replacement for Blizzard's default unit frames, including raid frames and raid tools", category: "UI", support: "Version 1.12.1", category_id: 2 , image: "http://img.xooimage.com/files41/1/5/a/wowscrnshot_110909_001350-15a3449.jpg", downloadlink: "/addons/ui/XPerl-Pack.zip")
ag_unitframe = Addon.create(name: "ag_UnitFrames", description: "Customizable unit frame addon.", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://livewow.su/_ld/5/570.jpg", dtime: 20, downloadlink: "/addons/ui/ag_UnitFrames.zip")
grids = Addon.create(name: "Grid", description: "The compact grid of units lets you select a group member quickly, while keeping a good overview of the whole group. It shows as much information as possible without overloading you. It allows you to customize what information you see, and how you see it. It works in both party and raid groups, and supports pets and vehicles.", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://chicanery.fibergeek.com/wp-content/uploads/2009/12/grid-description.png", dtime: 20, downloadlink: "/addons/ui/Grid.zip")
archud = Addon.create(name: "ArcHUD2", description: "ArcHUD displays smooth arcs around your character in the middle of the screen to inform you about the health and power (mana, rage, ...) of you, your pet, and your target. In addition, it shows casts, combo points, holy power, soul shards, and a couple of other things. It discretely fades when you are out of combat and at full health/power.", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://wowglobal.ru/_ld/4/24120577.jpg", dtime: 20, downloadlink: "/addons/ui/ArcHUD2.zip")
xpcounter = Addon.create(name: "XPCounter", description: "XpCounter shows a modified tooltip window for the standard experience bar containing various experience related information. You can also enable a dragable frame, that shows those info (or some of them, complete customizable) on screen.", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://media-curse.cursecdn.com/attachments/75/96/c39a40403dec85fc21eb8f99229d64ac.jpg", dtime: 20, downloadlink: "/addons/ui/XPCounter.zip")
ct = Addon.create(name: "CT_UnitFrames", description: "Unit frame mod that allows you to further customize the look and feel of the Blizzard unit frames.", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://i44.tinypic.com/11m58xg.jpg", dtime: 20, downloadlink: "/addons/ui/CT_UnitFrames.zip")
br = Addon.create(name: "brDamageText", description: "This mod displays the damage you do (to your target) in the targetframe(portrait). Helpful against all big enemies (for example MC Giants and Bosses), ", category: "UI", support: "Version 1.12.1", category_id: 2, image: "http://legacy.curseforge.com/media/images/2/21/brdamagetext-1-51-dufportrait-spellcrit.jpg", dtime: 20, downloadlink: "/addons/ui/brDamageText.zip")


#------------------ Auction House 3-------------------------------------------

auctioneer = Addon.create(name: "Auctioneer", description: "Auctioneer Suite provides you with the tools and data necessary to make those difficult auctioning decisions with ease. From purchasing to posting, the Auctioneer Suite provides time-tested tools to allow you more time to actually play your characters or play the market.", category: "Auction House", support: "Version 1.12.1", category_id: 3, image: "http://forum.monster-wow.com/index.php?app=downloads&module=display&section=screenshot&record=224&id=65&full=1", dtime: 20, downloadlink: "/addons/auction/Auctioneer.zip")
autoprofit = Addon.create(name: "AutoProfit", description: "AutoProfit v5.3 adds a small icon to merchant frames that allows you to sell every gray item in your inventory to the vendor instantly. You can also configure it to sell certain white items too. ", category: "Auction House", support: "Version 1.12.1", category_id: 3, image: "http://wowdes.net.ua/uploads/autoprofit.png", dtime: 20, downloadlink: "/addons/auction/AutoProfit.zip")
kc = Addon.create(name: "KC_Items", description: "KC Items is an addon conglomerate that is both feature rich and modular. By modular I mean that you can remove any of the modules that you chose to do so. However some modules depend on the functionality of other modules, and if you remove a module any dependent modules will be disabled. Each module is broken up into its own directory for easy removal. The following is a list of all the modules with a full description of each. Based on which of these modules you decide to use the functionality of KC_Items can change drastically.", category: "Auction House", support: "Version 1.12.1", category_id: 3, image: "http://legacy.curseforge.com/thumbman/images/1/588/200x143/kc-items-adv-search.jpg.-m1.png", dtime: 20, downloadlink: "/addons/auction/KC_Items.zip")
accountant = Addon.create(name: "Accountant", description: "Are you one of those people that at the end of the week, just can't figure out where your gold went? Do you want to know what your biggest expenses are? Accountant is an in dept Gold tracking ad don that tels you exactly how much your trip to the auction has cost you, what you spend on taxi costs, what you have earned from quests and many other things.", category: "Auction House", support: "Version 1.12.1", category_id: 3, image: "http://media-curse.cursecdn.com/attachments/17/337/fca1f52f1e3d75068df975c5731667f5.png", dtime: 20, downloadlink: "/addons/auction/Accountant.zip")
auctionfilter = Addon.create(name: "AuctionFilterPlus", description: "This mod adds a flyout panel of filters and display modifications, plus a reset button, to the Auction House.", category: "Auction House", support: "Version 1.12.1", category_id: 3, image: "http://www.blogcdn.com/wow.joystiq.com/media/2007/09/afp.jpg", dtime: 20, downloadlink: "/addons/auction/AuctionFilterPlus.zip")

#------------------ Actionbars 4-------------------------------------------

acetimer = Addon.create(name: "AceTimer", description: "AceTimer supports one-shot timers and repeating timers. All timers are stored in an efficient data structure that allows easy dispatching and fast rescheduling. Timers can be registered or canceled at any time, even from within a running timer, without conflict or large overhead.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "https://wowacereview.files.wordpress.com/2006/08/acetimer1.jpg", downloadlink: "/addons/actionbar/AceTimer.zip", dtime: 20)
bartender2 = Addon.create(name: "Bartender 2", description: "Bartender is a full ActionBar replacement mod. It provides you with all the features needed to fully customization most aspects of your action and related bars.", category: "Action Bars", support: "Version 1.12.1", category_id: 4 , image: "http://img.xooimage.com/files26/f/0/f/wowscrnshot_101210_012058-2146971.jpg", dtime: 20, downloadlink: "/addons/Bartender2.zip")
omnicc = Addon.create(name: "OmniCC", description: "OmniCC is an addon that adds text to items, spell and abilities that are on cooldown to indicate when they will be ready to use. In other words: it turns all the standard analogue cooldowns into digital ones.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://img4.hostingpics.net/pics/942724omniCC.png", downloadlink: "/addons/OmniCC.zip")
xloot = Addon.create(name: "XLoot", description: "Providing a large array of options to change how loot is presented, as well as allowing you to use Masque or ButtonFacade Skins, XLoot's job is to make looting more functional while still having a better form.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://forum.monster-wow.com/index.php?app=downloads&module=display&section=screenshot&record=298&id=77&full=1", downloadlink: "/addons/actionbar/XLoot.zip")
bongos = Addon.create(name: "Bongos Pack", description: "Bongos brings you new, totally customizeable interface including action bars, cast bars, minimap, frames and much more.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://wowaddons.snowolf.eu/uploads/g13_screen_2.jpg", downloadlink: "/addons/actionbar/Bongos-Pack.zip")
healbot = Addon.create(name: "HealBot", description: "Configure key mouse combos to cast any helpful spell on Players with active bars. Configure key mouse combos to cast any helpful spell on Players with non-active bars. Configure key mouse combos to cast any harmful spell on Enemy targets with active bars.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://healbot.darktech.org/index.php/availableskins/details/1/5/share-skins?contentbuilder_display_detail=1&contentbuilder_detail_file=70c151b9b752f382e0b301c452d4a888865f3d49", downloadlink: "/addons/actionbar/HealBot.zip")
ecastingbar = Addon.create(name: "eCastingBar", description: "eCastingBar is a movable and configurable casting bar replacement. It includes a Mirror Bar that handles Breathing, Feign Death, and Exhaustion, as well as a new Target Bar, showing what your target is casting.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://vig.extremetech.com/media/images/181062.jpg?thumb=y", downloadlink: "/addons/eCastingBar.zip")
fubar = Addon.create(name: "FuBar", description: "Fubar is a WoW addon that places horizontal panels where other addons can be plugged into. The addon displays a list of supported addons which have been installed and allows easy access to most commonly used options provided by supported addon plugins. It also displays in-game information at a glance.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://media-curse.cursecdn.com/attachments/13/523/54cfd1c628fc7da62aa04193198b4554.jpeg", downloadlink: "/addons/actionbar/FuBar-Complete-Pack.zip")
clique = Addon.create(name: "Clique", description: "Clique is a simple addon that enables powerful click-casting and hover-casting on your unit frames and in the 3D game world. You can bind virtually any mouse or keyboard combination to a spell or macro. In it's normal configuration this enables you to use the bindings over your unit frames in order to cast spells directly on that unit. This allows you to more quickly select both the spell to cast, and the target of the spell without requiring an extra click.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://chicanery.fibergeek.com/wp-content/uploads/2009/12/grid-description.png", downloadlink: "/addons/actionbar/Clique.zip")
cooldown = Addon.create(name: "Cooldown Timers", description: "Cooldown Timer Bars will scan your spellbook/inventory for skills/items that are in cooldown and will create draggable bars for your cooldowns.", category: "Action Bars", support: "Version 1.12.1", category_id: 4, image: "http://media-curse.cursecdn.com/attachments/0/918/a621f4d9554f979a2cfb8fe9b2ca01c1.jpg", downloadlink: "/addons/actionbar/CooldownTimers.zip")

#------------------ Questing 5 -------------------------------------------

atlasloot = Addon.create(name: "AtlasLoot", description: "AtlasLoot Enhanced is an UI mod allowing for loot tables of bosses to be browsed whenever needed within the game.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://forum.monster-wow.com/index.php?app=downloads&module=display&section=screenshot&record=326&id=18&full=1", dtime: 20, downloadlink: "/addons/quest/AtlasLoot.zip")
questie = Addon.create(name: "Questie", description: "Questie is a quest help addon for vanilla WoW. It's currently under continuing development.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://i.imgur.com/qbTepxD.png", dtime: 20, downloadlink: "/addons/quest/Questie.zip")
atlas = Addon.create(name: "Atlas", description: "Atlas is an addon for World of Warcraft that includes detailed maps for every instance in the game. Originally, Blizzard neglected to include maps for instances. However, after a number of years Blizzard began to include official maps for some instances.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://vignette3.wikia.nocookie.net/wowwiki/images/4/46/AtlasAddon.jpg/revision/latest?cb=20080421164944", dtime: 20, downloadlink: "/addons/quest/Atlas.zip")
atlasquest = Addon.create(name: "AtlasQuest", description: "AtlasQuest is an addon for a World of Warcraft addon called Atlas. It contains information and a list of quests for the Dungeons, Raids, and Battlegrounds", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://2.bp.blogspot.com/-QBhvK7Aqvbg/Td_elF8ofgI/AAAAAAAAAJM/T2BOs2L4XQ4/s1600/Blog+Atlas+Battleground.png", dtime: 20, downloadlink: "/addons/quest/AtlasQuest.zip")
fastquest = Addon.create(name: "FastQuest", description: "FastQuest Classic is an addon to enhance quest log displaying, quest tracking, and notification. This is an alternative to heavy duty add-ons like MonkeyQuest, Quest-I-On, etc. The difference is that the code is much smaller and faster, since it uses Blizzard's build-in components enhancing and improving them. But it does not have full set of features those addons offer, so try them and decide what is best for you!", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://legacy.curseforge.com/media/images/3/965/QuestLog.png", dtime: 20, downloadlink: "/addons/quest/FastQuest.zip")
killstolevel = Addon.create(name: "KillsToLevel", description: "Creates a dragable counter showing the estimated number of kills required to reach the next level.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://cdn-wow.mmoui.com/preview/pvw56603.png", dtime: 20, downloadlink: "/addons/quest/KillsToLevel.zip")
quickloot = Addon.create(name: "QuickLoot", description: "This addon picks up items from the loot window as quickly as possible (as latency allows).", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://2.bp.blogspot.com/-8rYtU354kX4/T-BucEeDv5I/AAAAAAAACMg/O6f2BR2ac4g/s1600/large+mithril+bound+chest+farming.jpg", dtime: 20, downloadlink: "/addons/quest/QuickLoot.zip")
uberquest = Addon.create(name: "UberQuest", description: "UberQuest is a drop-in replacement for Blizzard's Quest Log providing a dual pane view, full panes for the quest listing and a second full pane for the quest description itself. Plus, a powerful quest tracker/minion.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://s.cdn.wowinterface.com/preview/pvw12573.jpg", dtime: 20, downloadlink: "/addons/quest/UberQuest.zip")
beb = Addon.create(name: "Basic Bar", description: "Basic Experience Bar is a highly configurable add-on to cover (or replace if another add-on has hidden it) the default UI experience bar.", category: "Questing", support: "Version 1.12.1", category_id: 5, image: "http://cdn-wow.mmoui.com/preview/pvw21946.jpg", dtime: 20, downloadlink: "/addons/quest/BEB.zip")

#------------------ Boss 6 -------------------------------------------

threat = Addon.create(name: "KLHThreatMeter", description: "KLHThreatMeter is like a damage meter, except it records your threat. By monitoring all the abilities you use and checking your talents, armour set bonuses and buffs, the addon can recreate the threat list of a mob. This makes tank transitions simple, and allows DPS to maximise their damage without pulling aggro.", category: "Boss Encounters", support: "Version 1.12.1", category_id: 6, image: "http://www.blogcdn.com/wow.joystiq.com/media/2007/07/klh.jpg", dtime: 25, downloadlink: "/addons/boss/KLHThreatMeter.zip")
bigwig = Addon.create(name: "BigWigs", description: "Big Wigs is a boss encounter add-on. It consists of many individual encounter scripts, or boss modules; mini add-ons that are designed to trigger alert messages, timer bars, sounds, and so forth, for one specific raid encounter.", category: "Boss Encounters", support: "Version 1.12.1", category_id: 6, image: "http://s.cdn.wowinterface.com/preview/pvw48842.jpg", dtime: 20, downloadlink: "/addons/boss/BigWigs.zip")
recap = Addon.create(name: "Recap", description: "This AddOn will track and summarize the damage dealt and received by every participant in a fight around the user. Once installed, use /recap to summon or dismiss the window. Alternately, you can set up a key binding in options to toggle the window.", category: "Boss Encounters", support: "Version 1.12.1", category_id: 6, image: "http://media-curse.cursecdn.com/attachments/0/15/2b834b46e55a59a7c291d84ae916fd1a.jpg", dtime: 20, downloadlink: "/addons/boss/Recap.zip")

#------------------ Bags 7 -------------------------------------------

bagnon = Addon.create(name: "Bagnon", description: "Bagnon merges all of your bags into three windows: inventory, bank and guild bank. Beyond the basic all-in-one functionality", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://media-curse.cursecdn.com/attachments/74/147/4218c641028da24d233f5d25e6803d51.jpeg", dtime: 30, downloadlink: "/addons/bags/Bagnon.zip")
onebag = Addon.create(name: "OneBag", description: "OneBag is a replacement for the default game bags that combines all the bags into one frame. There are already addons out there that do this, so why OneBag? Mainly because I wanted a simpler, more system-friendly bag. OneBag doesn't entirely rewrite the bag-handling interface like others do. It simply rearranges the bags into one and allows the default UI to continue managing the bag slots.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "https://nedruid.files.wordpress.com/2007/01/onebag-open.jpg", dtime: 20, downloadlink: "/addons/bags/OneBag.zip")
allinone = Addon.create(name: "AllInOneInventory", description: "All In One Inventory ( AIOI ) allows you to view your inventory without caring about bags.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://legacy.curseforge.com/media/images/0/62/allinoneinventory-0-22-and-higher.jpg", dtime: 20, downloadlink: "/addons/bags/AllInOneInventory.zip")
outfitter = Addon.create(name: "Outfitter", description: "Outfitter is an equipment management addon which gives you fast access to multiple outfits to optimize your abilities in PvE and PvP, automated equip and unequip for convenience doing a variety of activities, or to enhance role-playing.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://media-curse.cursecdn.com/attachments/2/817/92d016f98098de745dae87306556b7b3.png", dtime: 20, downloadlink: "/addons/bags/Outfitter.zip")
onebank = Addon.create(name: "OneBank", description: "OneBank3 is the latest in a long line of bank bag replacements for the default bank bags that will combine all of your bags into one frame.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://cdn-wow.mmoui.com/preview/pvw21324.png", dtime: 20, downloadlink: "/addons/bags/OneBank.zip")
fruityloots = Addon.create(name: "FruityLoots", description: "Places the Loot Box right under your mousecursor so you only have to click the left mousebutton to loot each item. When enabled it jumps from item to item and also to the down arrow when there are more items to loot, plus it's auto-hiding the Loot Box when it's empty.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://wowjp.net/_fr/135/8906958.jpg", dtime: 20, downloadlink: "/addons/bags/FruitLoots.zip")
oneview = Addon.create(name: "OneView", description: "A plugin for OneBag and Bank which saves your character information so you can get your bank contents from anywhere.", category: "Bags", support: "Version 1.12.1", category_id: 7, image: "http://hydra-media.cursecdn.com/old.wowace.com/c/c5/OneView.jpg?version=75bed91ced7eecab33415892ed7917a5", dtime: 20, downloadlink: "/addons/bags/OneView.zip")



#category seeds
nav = Category.create(name: "Navigation/Maps", image: "http://jeffstieler.com/app/uploads/2009/03/picture-2.png", category_id: 1)
ui = Category.create(name: "UI", image: "http://imgur.com/eCurpGn", category_id: 2)
ah = Category.create(name: "Auction House", image: "http://imgur.com/BGFlDoa", category_id: 3)
toolbar = Category.create(name: "Action Bars", image: "http://imgur.com/P6Fx4IZ", category_id: 4)
questing = Category.create(name: "Questing", image: "http://imgur.com/SWIrR2h", category_id: 5)
boss = Category.create(name: "Boss Encounters", image: "http://vignette4.wikia.nocookie.net/wowwiki/images/f/f5/Ragnaros_Cataclysm.png/revision/latest?cb=20150401130808", category_id: 6)
bags = Category.create(name: "Bags", image: "http://imgur.com/rF1ogMT", category_id: 7)